project_id = "zrmhhnepzbwbihdshwcm"

[functions.check-ban]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.company-join]
verify_jwt = false

[functions.reset-company-data]
verify_jwt = false
